version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres_local
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql #Need to create the liquibase's schemas (only liquibase pre-config)
      - postgres-data:/var/lib/postgresql/data #Do not add the ./ to the beginning it changes it from a volume to a file system and postgres wont bind right. reference: https://dotnetninja.net/2020/02/running-postgresql-in-a-container-on-windows-10/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  postgres-data:
    driver: local
